CRAIGSLIST_CITIES = [
    "toronto"
]
CRAIGSLIST_BASE_URL = "https://{}.craigslist.org/d/computer-gigs/search/cpg"
KEYWORDS = [
    "website development",
    "wordpress",
    "mobile app",
    "php",
    "laravel",
    "mern",
    "mean",
    "next.js",
    "react",
    "node.js",
    "full stack",
    "devops",
    "blockchain",
    "ethereum",
    "solidity",
    "nft",
    "3d artist",
    "digital marketing",
    "seo",
    "social media",
    "shopify",
    "wix",
    "e-commerce",
    "python",
    "django",
    "javascript",
    "typescript",
    "vue.js",
    "angular",
    "aws",
    "cloud",
    "database",
    "sql",
    "nosql",
    "mongodb",
    "postgresql",
    "ui/ux",
    "web design",
    "graphic design",
    "data science",
    "machine learning",
    "ai",
    "automation",
    "qa testing",
    "software testing",
    "system admin",
    "network",
    "cyber security",
    "flutter",
    "swift",
    "ios development",
    "android development",
    "game development",
    "unity",
    "unreal engine",
    "c++",
    "c#",
    "java",
    "ruby",
    "ruby on rails",
    "go",
    "golang",
    "kotlin",
    "rust",
    "scala",
    "svelte",
    "figma",
    "adobe xd",
    "photoshop",
    "illustrator",
    "indesign",
    "after effects",
    "premiere pro",
    "3d modeling",
    "blender",
    "maya",
    "zbrush",
    "content creation",
    "video editing",
    "animation",
    "docker",
    "kubernetes",
    "terraform",
    "jenkins",
    "gitlab ci",
    "github actions",
    "ci/cd",
    "microservices",
    "serverless",
    "lambda",
    "firebase",
    "azure",
    "gcp",
    "google cloud",
    "twilio",
    "stripe",
    "payment integration",
    "api development",
    "rest api",
    "graphql",
    "web scraping",
    "data mining",
    "data analysis",
    "excel",
    "power bi",
    "tableau",
    "r programming",
    "statistics",
    "big data",
    "hadoop",
    "spark",
    "kafka",
    "data engineering",
    "etl",
    "natural language processing",
    "nlp",
    "computer vision",
    "opencv",
    "tensorflow",
    "pytorch",
    "deep learning",
    "reinforcement learning",
    "chatbot",
    "web3",
    "defi",
    "smart contract",
    "cryptocurrency",
    "backend",
    "frontend",
    "ui developer",
    "ux researcher",
    "user research",
    "prototyping",
    "wireframing",
    "responsive design",
    "mobile first",
    "cross platform",
    "pwa",
    "progressive web app",
    "web components",
    "cms",
    "drupal",
    "joomla",
    "magento",
    "opencart",
    "prestashop",
    "squarespace",
    "database design",
    "data modeling",
    "redis",
    "elasticsearch",
    "cassandra",
    "dynamodb",
    "mariadb",
    "mysql",
    "sqlite",
    "oracle",
    "security audit",
    "penetration testing",
    "ethical hacking",
    "vulnerability assessment",
    "ciso",
    "it support",
    "helpdesk",
    "technical support",
    "system engineer",
    "network engineer",
    "cisco",
    "juniper",
    "virtualization",
    "vmware",
    "hyper-v",
    "windows server",
    "linux admin",
    "bash scripting",
    "powershell",
    "automation script",
    "cron job",
    "email marketing",
    "content marketing",
    "social media management",
    "ppc",
    "google ads",
    "facebook ads",
    "marketing automation",
    "analytics",
    "google analytics",
    "conversion optimization",
    "a/b testing",
    "user testing",
    "accessibility",
    "wcag",
    "seo optimization",
    "technical seo",
    "local seo"
]
REMOTE_KEYWORDS = [
    "remote ok",
    "remote only",
    "work from home",
    "telecommute",
    "fully remote",
    "anywhere",
    "virtual",
    "can be remote"
]
NON_REMOTE_KEYWORDS = [
    "local only",
    "local",
    "no remote",
    "on-site",
    "in-person",
    "usa only",
    "native only",
    "MUST BE LOCAL"
]
