CRAIGSLIST_CITIES = [
    "auburn",
    "bham",
    "dothan"
]
CRAIGSLIST_BASE_URL = "https://{}.craigslist.org/search/cpg"
KEYWORDS = [
    "website development",
    "wordpress",
    "mobile app",
    "php",
    "laravel",
    "mern",
    "mean",
    "next.js",
    "react",
    "node.js",
    "full stack",
    "devops",
    "blockchain",
    "ethereum",
    "solidity",
    "nft",
    "3d artist",
    "digital marketing",
    "seo",
    "social media",
    "shopify",
    "wix",
    "e-commerce",
    "python",
    "django",
    "javascript",
    "typescript",
    "vue.js",
    "angular",
    "aws",
    "cloud",
    "database",
    "sql",
    "nosql",
    "mongodb",
    "postgresql",
    "ui/ux",
    "web design",
    "graphic design",
    "data science",
    "machine learning",
    "ai",
    "automation",
    "qa testing",
    "software testing",
    "system admin",
    "network",
    "cyber security",
    "flutter",
    "swift",
    "ios development",
    "android development",
    "game development"
]
REMOTE_KEYWORDS = [
    "remote ok",
    "remote only",
    "work from home",
    "telecommute",
    "fully remote",
    "anywhere",
    "virtual",
    "can be remote"
]
NON_REMOTE_KEYWORDS = [
    "local only",
    "local",
    "no remote",
    "on-site",
    "in-person",
    "usa only",
    "native only",
    "MUST BE LOCAL"
]
